dependabot-auto-merge:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/dependabot-auto-merge.yml"

dependabot-security-alert:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/dependabot-security-alert.yml"

major-tag-updater:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/major-tag-updater.yml"

pages-yard:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/pages-yard.yml"

rbs-collection-updater:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/rbs-collection-updater.yml"

release_gem:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/release_gem.yml"

terraform-auto-merge:
  - changed-files:
      - any-glob-to-any-file: ".github/actions/terraform-auto-merge/**"

terraform-version-updater:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/terraform-version-updater.yml"
